package com.api.routes.products.sql;

public enum ProducSql {
  FIND_PRODUCT_BY_ID(
    "SELECT " +
      "IPT.PRODUCTID, " +
      "IPT.NAME AS PRODUCTNAME, " +
      "IPT.CATEGORYID, " +
      "IPC.NAME AS CATEGORYNAME, " +
      "IPT.SUPPLIERID, " +
      "ISL.NAME AS SUPPLIERNAME, " +
      "IPT.ACTIVE " +
    "FROM TB_IMS_PRODUCTS IPT " +
      "JOIN TB_IMS_PRODUCTCATEGORIES IPC ON (IPT.CATEGORYID = IPC.PRODUCTCATEGORYID) " +
      "JOIN TB_IMS_SUPPLIERS ISL ON (IPT.SUPPLIERID = ISL.SUPPLIERID) " +
    "WHERE IPT.ACTIVE = 1 AND IPT.PRODUCTID = ?"
  ),
  FIND_PRODUCT(
    "SELECT " +
      "IPT.PRODUCTID, " +
      "IPT.NAME AS PRODUCTNAME, " +
      "IPT.CATEGORYID, " +
      "IPC.NAME AS CATEGORYNAME, " +
      "IPT.SUPPLIERID, " +
      "ISL.NAME AS SUPPLIERNAME, " +
      "IPT.ACTIVE " +
    "FROM TB_IMS_PRODUCTS IPT " +
      "JOIN TB_IMS_PRODUCTCATEGORIES IPC ON (IPT.CATEGORYID = IPC.PRODUCTCATEGORYID) " +
      "JOIN TB_IMS_SUPPLIERS ISL ON (IPT.SUPPLIERID = ISL.SUPPLIERID) " +
    "WHERE IPT.ACTIVE = 1"
  ),
  FIND_ALL_PRODUCTS(
    "SELECT " +
      "IPT.PRODUCTID, " +
      "IPT.NAME AS PRODUCTNAME, " +
      "IPT.CATEGORYID, " +
      "IPC.NAME AS CATEGORYNAME, " +
      "IPT.SUPPLIERID, " +
      "ISL.NAME AS SUPPLIERNAME, " +
      "IPT.ACTIVE " +
    "FROM TB_IMS_PRODUCTS IPT " +
      "JOIN TB_IMS_PRODUCTCATEGORIES IPC ON (IPT.CATEGORYID = IPC.PRODUCTCATEGORYID) " +
      "JOIN TB_IMS_SUPPLIERS ISL ON (IPT.SUPPLIERID = ISL.SUPPLIERID) "
  ),
  ACTIVE_PRODUCT(
    "UPDATE TB_IMS_PRODUCTS " +
    "SET ACTIVE = 1 " +
    "WHERE PRODUCTID = ?"
  ),
  DELETE_PRODUCT(
    "UPDATE TB_IMS_PRODUCTS " +
    "SET ACTIVE = 0 " +
    "WHERE PRODUCTID = ?"
  );

  private final String sql;

  ProducSql(String sql) {
    this.sql = sql;
  }

  public String getQuery() {
    return sql;
  }
}
